Release v1.3.1
iver-wharf/wharf-web pull request #38
Opened 2021-06-17 08:14 UTC by jilleJr

The bugfix from #35 is the most crucial thing in this release.

## Changes

- Added a URL validator to the add project/provider forms. (#6)

- Added newly generated code for each Swagger-based API clients inside `projects` directory inside repository: (#34)
  - `api-client`: v4.1.0
  - `import-github-client`: v2.0.0-rc
  - `import-gitlab-client`: v1.2.0-rc
  - `import-azuredevops-client`: v1.2.0-rc

  Cleaned up old files, where some collided on case-insensitive file systems, such as `mainAzureDevOpsPrResource.ts` vs `mainAzureDevOpsPRResource.ts`.

- Fixed provider APIs getting main API's config, leading to all provider API requests pointing to wrong base URL. (#35)

2021-06-17 14:47 UTC, Pikabanga approved these changes

2021-06-18 13:53 UTC, fredx30 requested changes
This seems to be missing the bug fix concerning the missing validator file.

2021-06-23 05:58 UTC, iverestefans approved these changes

2021-06-28 09:07 UTC, Alexamakans approved these changes

2021-07-02 09:27 UTC, merged